### ISSUE TITLE
independent partner install 2

### ISSUE THREAD

**Issue by rmkraus** [project-faros/cluster-manager#64]
- [x] Make hardware config a list in documentation.
- [x] expired certs during install
  - issue with system clock
- [x] ~~cleanup command~~ -> tracked in #72 
  - remove vm's
  - remove named
  - remove dhcpd
- [x] ~~preflight script ?~~ -> Tracked in #73 
- [x] ~~allow more than one faros command to be run at a time~~ -> tracked in #65 
  - use pods
